development:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'v2-latest'
  auth:
    key     : <%= ENV['TRANSLOADIT_KEY_ID'] %>
    secret  : <%= ENV['TRANSLOADIT_SECRET']  %> # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    s3_store: 'd0625590ecd611e5adfcdb4e56f019b1'
    # # template defined inline
    # image_resize:
    #   steps:
    #     resize:
    #       robot : '/image/resize'
    #       format: 'jpg'
    #       width : 320
    #       height: 200

production:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'v2-latest'
  auth:
    key     : <%= ENV['TRANSLOADIT_KEY_ID'] %>
    secret  : <%= ENV['TRANSLOADIT_SECRET'] %> # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    s3_store: 'd0625590ecd611e5adfcdb4e56f019b1'

    # # template defined inline
    # image_resize:
    #   steps:
    #     resize:
    #       robot : '/image/resize'
    #       width : 320
    #       height: 200
